---
# グローバル変数をローカル変数に変換
- name: Set _regdata
  set_fact:
    _regdata: {}
  delegate_to: localhost

# _ita_record_after から Noを抜いたデータを作成
# valueが空の場合も抜いておく
- name: Set Registration Data
  set_fact:
    _regdata: "{{ _regdata | combine({item.key:item.value}, recursive=True) }}"
  loop: "{{ _compareloop|dict2items  }}"
  when: item.key != "No" and item.value and item.value != "None"
  delegate_to: localhost

# レコードにsys_idがないやつは追加
- name: Call add_record.yml
  include_tasks: servicenow/add_record.yml
  when: not _compareloop.sys_id

# レコードにsys_idがあるやつは更新
- name: Call change_record.yml
  include_tasks: servicenow/change_record.yml
  when: _compareloop.sys_id
