---
# ITAから連携対象のメニューIDを取得
- name: Get MenuID = Tablename
  uri:
    url: "https://{{ __loginhostname__ }}/default/menu/07_rest_api_ver1.php?no=0000600001"
    headers:
      Host: "{{ __loginhostname__ }}:443"
      Content-type: "application/json"
      Authorization: "{{ GBL_AUTHORIZATION }}"
      X-Command: FILTER
    method: POST
    status_code: 200
    validate_certs: no
    body_format: json
    body:
      "1":
        "NORMAL": "0"
  register: _tablename_result
  environment:
    no_proxy: "{{ __loginhostname__ }}"
  delegate_to: localhost


