---
- name: Set _ita_record_after
  set_fact:
    _ita_record_after: []
  delegate_to: localhost

# REST用のbodyの作成
- name: Set _body
  set_fact:
    _body: >-
      {%- set tmpdict = {} -%}
      {%- set _ =  tmpdict.update( { "1": { "NORMAL": "0" }}) -%}
      {%- set _ =  tmpdict.update( { _lastupdate_num: { "RANGE" : { "START": _filter_date }}} ) -%}
      {{ tmpdict }}
  delegate_to: localhost

# ITAから連携対象を取得
- name: Get ITA record
  uri:
    url: "https://{{ __loginhostname__ }}/default/menu/07_rest_api_ver1.php?no={{ _menu_id }}"
    headers:
      Host: "{{ __loginhostname__ }}:443"
      Content-type: "application/json"
      Authorization: "{{ GBL_AUTHORIZATION }}"
      X-Command: FILTER
    method: POST
    status_code: 200
    validate_certs: no
    body_format: json
    body: "{{ _body }}"
  register: _ita_record
  environment:
    no_proxy: "{{ __loginhostname__ }}"
  delegate_to: localhost

- block:
  # ITAから項目名紐づけ表を取得
  - name: Call get_itemname.yml
    include_tasks: ita/get_itemname.yml

  # 辞書形式にした連携対象のキーをServicenow用のキーに変更
  # 配列へ抜出し
  - name: Set _ita_tmpitemlist
    set_fact:
      _ita_tmpitemlist: >-
        {%- set tmplist = [] -%}
        {%- for valloop in _ita_record.json.resultdata.CONTENTS.BODY -%}
        {%-   set tmplist2 = [] -%}
        {%-   for val in valloop -%}
        {%-     if loop.index == 3 or loop.index == 4 or loop.index > 10 and loop.index < _ita_record.json.resultdata.CONTENTS.BODY[0] |length - 4 -%}
        {%-       set _ =  tmplist2.append(val) -%}
        {%-     endif -%}
        {%-   endfor -%}
        {%-   set _ =  tmplist.append(tmplist2) -%}
        {%- endfor -%}
        {{ tmplist }}
    delegate_to: localhost

  # Key書き換え
  - name: Set _ita_itemlist
    set_fact:
      _ita_itemlist: >-
        {%- set tmplist = [] -%}
        {%- for valloop in _ita_tmpitemlist -%}
        {%-   set tmplist2 = [] -%}
        {%-   if loop.index0 == 0 -%}
        {%-     for val in valloop -%}
        {%-       if val in _itemname_dict -%}
        {%-         set _ =  tmplist2.append(_itemname_dict[val]) -%}
        {%-       else -%}
        {%-         set _ =  tmplist2.append(val) -%}
        {%-       endif -%}
        {%-     endfor -%}
        {%-     set _ =  tmplist.append(tmplist2) -%}
        {%-   else -%}
        {%-     set _ =  tmplist.append(valloop) -%}
        {%-   endif -%}
        {%- endfor -%}
        {{ tmplist }}
    delegate_to: localhost

  - name: Set _ita_itemval
    set_fact:
      _ita_record_after: >-
        {%- set tmplist = [] -%}
        {%- for valloop in _ita_itemlist -%}
        {%-   if loop.index > 1 -%}
        {%-     set tmpdic = {} -%}
        {%-     for val in valloop -%}
        {%-       if "パラメータ" not in _ita_itemlist[0][loop.index0] and "ホスト名" not in _ita_itemlist[0][loop.index0] and  "代入順序" not in _ita_itemlist[0][loop.index0]-%}
        {%-         if val -%}
        {%-           set _ =  tmpdic.update( { _ita_itemlist[0][loop.index0]: val }) -%}
        {%-         else -%}
        {%-           set _ =  tmpdic.update( { _ita_itemlist[0][loop.index0]: "" }) -%}
        {%-         endif -%}
        {%-       endif -%}
        {%-     endfor -%}
        {%-     set _ =  tmplist.append(tmpdic) -%}
        {%-   endif -%}
        {%- endfor -%}
        {{ tmplist }}
    delegate_to: localhost

  when: _ita_record.json.resultdata.CONTENTS.RECORD_LENGTH > 0
