---
# 登録用配列への追加フラグ宣言
- name: Set addflag and loopcount
  set_fact:
    addflag: "True"
  delegate_to: localhost

# sys_idが同じかつ基準日時が大きいやつが存在する場合
# 登録用の配列に追加しない
- name: Check Duplication
  set_fact:
    addflag: "False"
  when:
    - _ita_record_loop[ _sys_id_num | int ]
    - item[ _sys_id_num | int ] == _ita_record_loop[ _sys_id_num | int ]
    - item[6] > _ita_record_loop[6] 
  loop: "{{ _ita_record.json.resultdata.CONTENTS.BODY }}"
  loop_control:
    extended: yes
  delegate_to: localhost

# 配列に追加
- name: Add _ita_record_before
  set_fact:
    _ita_record_before: "{{ _ita_record_before + [_ita_record_loop] }}"
  when: addflag
  delegate_to: localhost