---
# 配列へ抜出し
- name: Set _ita_itemlist
  set_fact:
    _ita_itemlist: >-
      {%- set tmplist = [] -%}
      {%- for valloop in _ita_record_before -%}
      {%-   set tmplist2 = [] -%}
      {%-   for val in valloop -%}
      {%-     if loop.index == 3 or loop.index == 4 or loop.index > 10 and loop.index < _ita_record_before[0] |length - 4 -%}
      {%-       if val is not none and 'パラメータ' in val -%}
      {%-         set _ =  tmplist2.append(val | regex_replace('^.*(?<=/)')) -%}
      {%-       else -%}
      {%-         set _ =  tmplist2.append(val) -%}
      {%-       endif -%}
      {%-     endif -%}
      {%-   endfor -%}
      {%-   set _ =  tmplist.append(tmplist2) -%}
      {%- endfor -%}
      {{ tmplist }}
  delegate_to: localhost

# 辞書形式に成型
- name: Set _ita_itemval
  set_fact:
    _ita_itemdiclist: >-
      {%- set tmplist = [] -%}
      {%- for valloop in _ita_itemlist -%}
      {%-   if loop.index > 1 -%}
      {%-     set tmpdic = {} -%}
      {%-     for val in valloop -%}
      {%-       set _ =  tmpdic.update( { _ita_itemlist[0][loop.index0]: val }) -%}
      {%-     endfor -%}
      {%-     set _ =  tmplist.append(tmpdic) -%}
      {%-   endif -%}
      {%- endfor -%}
      {{ tmplist }}
  delegate_to: localhost