---
# 参照の場合
- block:
  # 結果の比較
  - name: Check Result for link
    fail:
      msg: "レコードの登録に失敗しました。 ServiceNow: {{  _register.record[_regdict.key].value }} ITA: {{ _regdict.value }}"
    when: _register.record[_regdict.key].value | string != _regdict.value | string
    delegate_to: localhost

  when: "'value' in _register.record[_regdict.key]"

- block:
  # 結果の比較
  - name: Check Result for value
    fail:
      msg: "レコードの登録に失敗しました。 ServiceNow: {{  _register.record[_regdict.key] }} ITA: {{ _regdict.value }}"
    when: _register.record[_regdict.key] | string != _regdict.value | string
    delegate_to: localhost

  when: "'value' not in _register.record[_regdict.key]"