---
# 紐付け表の有無判定に利用
- name: Set _ref_menu_id
  set_fact:
    _ref_menu_id: "0"

# ServiceNowへレコード追加
- name: Add Record
  servicenow.servicenow.snow_record:
    username: "{{ VAR_servicenow_user }}"
    password: "{{ VAR_servicenow_password}}"
    instance: "{{ VAR_servicenow_instance }}"
    table: "{{ _mainloop[5] }}"
    state: present
    data: "{{ _regdata }}"
  register: _register
  environment: 
    - "{{ _environment }}"
  delegate_to: localhost

# 結果の確認
- name: Call check_results.yml
  include_tasks: common/check_results.yml
  loop: "{{ _regdata | dict2items }}"
  loop_control:
    loop_var: _regdict
    extended: yes

# 紐付け表の有無確認
- name: Call get_reference_menuid.yml
  include_tasks: ita/get_reference_menuid.yml

# 紐付け表のsys_idを登録
- name: Call add_sys_id_for_reference.yml
  include_tasks: ita/add_sys_id_for_reference.yml
  when: _ref_menu_id != "0"

# レコードにsys_idを登録
- name: Call add_sys_id.yml
  include_tasks: ita/add_sys_id.yml
  when: _ref_menu_id == "0"

# 対象レコードにServiceNow最終連携日時を登録
- name: Call change_cooperation_time.yml
  include_tasks: ita/change_cooperation_time.yml