---
# ServiceNowへレコード追加
- name: Add Record
  servicenow.servicenow.snow_record:
    username: "{{ VAR_servicenow_user }}"
    password: "{{ VAR_servicenow_password}}"
    instance: "{{ VAR_servicenow_instance }}"
    table: "{{ _mainloop[5] }}"
    state: present
    data: "{{ _compareloop }}"
  register: _register
  environment: 
    - "{{ _environment }}"
  delegate_to: localhost

# 結果の確認
- name: Call check_results.yml
  include_tasks: common/check_results.yml
  loop: "{{ _compareloop | dict2items }}"
  loop_control:
    loop_var: _regdict
    extended: yes

