---
# ServiceNowのレコード削除
- name: Delete Record 
  servicenow.servicenow.snow_record:
    username: "{{ VAR_servicenow_user }}"
    password: "{{ VAR_servicenow_password}}"
    instance: "{{ VAR_servicenow_instance }}"
    table: "{{ _mainloop[5] }}"
    state: absent
    number: "{{ delete_val }}"
    lookup_field: sys_id
  register: result_async
  environment: 
    - "{{ _environment }}"
  delegate_to: localhost
