---
# ServiceNowのレコードを検索
- name: Find Record
  servicenow.servicenow.snow_record_find:
    username: "{{ VAR_servicenow_user }}"
    password: "{{ VAR_servicenow_password}}"
    instance: "{{ VAR_servicenow_instance }}"
    max_records: "{{ GBL_MAX_RECORDS }}"
    raise_on_empty: False 
    table: "{{ _mainloop[5] }}"
    query:
      AND:
        not_equals:
          sys_id: ""
  register: _find_register
  environment:
    - "{{ _environment }}"
  delegate_to: localhost
